# Configuration constants for the application

# News API Configuration
# IMPORTANT: Replace with your actual key from newsapi.org
NEWS_API_KEY = "e7547b36fd0f4ffdb639fc2153d13119"

# NIFTY 200 Stock Tickers
NIFTY_200_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'BHARTIARTL.NS', 
    'HINDUNILVR.NS', 'SBIN.NS', 'LICI.NS', 'ITC.NS', 'HCLTECH.NS', 'LT.NS', 'KOTAKBANK.NS', 
    'BAJFINANCE.NS', 'AXISBANK.NS', 'ADANIENT.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'ASIANPAINT.NS', 
    'TITAN.NS', 'NTPC.NS', 'TATAMOTORS.NS', 'ONGC.NS', 'ADANIGREEN.NS', 'ULTRACEMCO.NS', 
    'ADANIPORTS.NS', 'DMART.NS', 'BAJAJFINSV.NS', 'COALINDIA.NS', 'POWERGRID.NS', 'NESTLEIND.NS',
    'TATASTEEL.NS', 'M_M.NS', 'JSWSTEEL.NS', 'WIPRO.NS', 'SBILIFE.NS', 'GRASIM.NS', 'HINDALCO.NS', 
    'ADANIPOWER.NS', 'VEDL.NS', 'INDUSINDBK.NS', 'LTIM.NS', 'PIDILITIND.NS', 'BRITANNIA.NS', 
    'TECHM.NS', 'EICHERMOT.NS', 'CIPLA.NS', 'GAIL.NS', 'TATACONSUM.NS', 'APOLLOHOSP.NS', 
    'DRREDDY.NS', 'HDFCLIFE.NS', 'BAJAJ-AUTO.NS', 'TATAPOWER.NS', 'HEROMOTOCO.NS', 'SHREECEM.NS', 
    'DIVISLAB.NS', 'BPCL.NS', 'UPL.NS', 'INDIGO.NS', 'AMBUJACEM.NS', 'IOC.NS', 'PFC.NS', 'HAL.NS', 
    'BEL.NS', 'SIEMENS.NS', 'HAVELLS.NS', 'CHOLAFIN.NS', 'BAJAJHLDNG.NS', 'ABB.NS', 'DLF.NS', 
    'BOSCHLTD.NS', 'INDHOTEL.NS', 'BANKBARODA.NS', 'CANBK.NS', 'PNB.NS', 'UNIONBANK.NS', 
    'TRENT.NS', 'GODREJCP.NS', 'DABUR.NS', 'MARICO.NS', 'SAIL.NS', 'AUROPHARMA.NS', 'LUPIN.NS', 
    'TORNTPOWER.NS', 'BIOCON.NS', 'PETRONET.NS', 'ZEEL.NS', 'INDUSTOWER.NS', 'JUBLFOOD.NS', 
    'IDFCFIRSTB.NS', 'IRCTC.NS', 'ZOMATO.NS', 'POLICYBZR.NS', 'NYKAA.NS', 'PAYTM.NS'
]

# Technical Analysis Parameters
RSI_OVERSOLD = 40
RSI_OVERBOUGHT = 70
ADX_STRONG_TREND = 25

# Fundamental Analysis Thresholds
PE_HEALTHY = 25
PE_HIGH = 60
PEG_GOOD_MAX = 1.2
PEG_HIGH = 2
PB_LOW = 3
PB_HIGH = 7
PROFIT_MARGIN_HIGH = 0.10
PROFIT_MARGIN_LOW = 0.05
ROE_STRONG = 0.15
ROE_WEAK = 0.10
DEBT_EQUITY_LOW = 100
DEBT_EQUITY_HIGH = 200