import streamlit as st
import pandas as pd
import io


@st.cache_data
def load_ticker_list():
    """Load the ticker list for NIFTY 500 stocks"""
    try:
        nifty_500_csv = '''Company Name,Industry,Symbol
360 ONE WAM LTD.,Financial Services,360ONE
3M INDIA LTD.,Diversified,3MINDIA
AARTI INDUSTRIES LTD.,Chemicals,AARTIIND
ABB INDIA LTD.,Capital Goods,ABB
ABBOTT INDIA LTD.,Healthcare,ABBOTINDIA
ADANI ENERGY SOLUTIONS LTD.,Power,ADANIENSOL
ADANI ENTERPRISES LTD.,Metals & Mining,ADANIENT
ADANI GREEN ENERGY LTD.,Power,ADANIGREEN
ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.,Services,ADANIPORTS
ADANI POWER LTD.,Power,ADANIPOWER
ADANI TOTAL GAS LTD.,Oil Gas & Consumable Fuels,ATGL
ADITYA BIRLA CAPITAL LTD.,Financial Services,ABCAPITAL
ADITYA BIRLA FASHION AND RETAIL LTD.,Consumer Services,ABFRL
AEGIS LOGISTICS LTD.,Services,AEGISCHEM
AETHER INDUSTRIES LTD.,Chemicals,AETHER
AFFLE (INDIA) LTD.,IT,AFFLE
AJANTA PHARMA LTD.,Healthcare,AJANTPHARM
ALKEM LABORATORIES LTD.,Healthcare,ALKEM
ALLCARGO LOGISTICS LTD.,Services,ALLCARGO
ALOK INDUSTRIES LTD.,Textiles,ALOKINDS
AMBER ENTERPRISES INDIA LTD.,Consumer Durables,AMBER
AMBUJA CEMENTS LTD.,Construction Materials,AMBUJACEM
ANGEL ONE LTD.,Financial Services,ANGELONE
APAR INDUSTRIES LTD.,Capital Goods,APARINDS
APOLLO HOSPITALS ENTERPRISE LTD.,Healthcare,APOLLOHOSP
APOLLO TYRES LTD.,Automobile and Auto Components,APOLLOTYRE
APTUS VALUE HOUSING FINANCE INDIA LTD.,Financial Services,APTUS
ASHOK LEYLAND LTD.,Automobile and Auto Components,ASHOKLEY
ASIAN PAINTS LTD.,Consumer Durables,ASIANPAINT
ASTRAL LTD.,Construction Materials,ASTRAL
AU SMALL FINANCE BANK LTD.,Financial Services,AUBANK
AVENUE SUPERMARTS LTD.,Consumer Services,DMART
AXIS BANK LTD.,Financial Services,AXISBANK
BAJAJ AUTO LTD.,Automobile and Auto Components,BAJAJ-AUTO
BAJAJ FINANCE LTD.,Financial Services,BAJFINANCE
BAJAJ FINSERV LTD.,Financial Services,BAJFINSV
BAJAJ HOLDINGS & INVESTMENT LTD.,Financial Services,BAJAJHLDNG
BALKRISHNA INDUSTRIES LTD.,Automobile and Auto Components,BALKRISIND
BALRAMPUR CHINI MILLS LTD.,FMCG,BALRAMCHIN
BANDHAN BANK LTD.,Financial Services,BANDHANBNK
BANK OF BARODA,Financial Services,BANKBARODA
BANK OF INDIA,Financial Services,BANKINDIA
BATA INDIA LTD.,Consumer Durables,BATAINDIA
BHARAT DYNAMICS LTD.,Capital Goods,BDL
BHARAT ELECTRONICS LTD.,Capital Goods,BEL
BHARAT FORGE LTD.,Automobile and Auto Components,BHARATFORG
BHARAT HEAVY ELECTRICALS LTD.,Capital Goods,BHEL
BHARTI AIRTEL LTD.,Telecommunication,BHARTIARTL
BIOCON LTD.,Healthcare,BIOCON
BIRLASOFT LTD.,IT,BSOFT
BLUE DART EXPRESS LTD.,Services,BLUEDART
BOSCH LTD.,Automobile and Auto Components,BOSCHLTD
BPCL,Oil Gas & Consumable Fuels,BPCL
BRIGADE ENTERPRISES LTD.,Realty,BRIGADE
BRITANNIA INDUSTRIES LTD.,FMCG,BRITANNIA
CAN FIN HOMES LTD.,Financial Services,CANFINHOME
CANARA BANK,Financial Services,CANBK
CASTROL INDIA LTD.,Oil Gas & Consumable Fuels,CASTROLIND
CEAT LTD.,Automobile and Auto Components,CEATLTD
CENTRAL BANK OF INDIA,Financial Services,CENTRALBK
CESC LTD.,Power,CESC
CG POWER AND INDUSTRIAL SOLUTIONS LTD.,Capital Goods,CGPOWER
CHAMBAL FERTILISERS & CHEMICALS LTD.,Chemicals,CHAMBLFERT
CHOLAMANDALAM INVESTMENT AND FINANCE COMPANY LTD.,Financial Services,CHOLAFIN
CIPLA LTD.,Healthcare,CIPLA
COAL INDIA LTD.,Oil Gas & Consumable Fuels,COALINDIA
COCHIN SHIPYARD LTD.,Capital Goods,COCHINSHIP
COFORGE LTD.,IT,COFORGE
COLGATE-PALMOLIVE (INDIA) LTD.,FMCG,COLPAL
CONTAINER CORPORATION OF INDIA LTD.,Services,CONCOR
COROMANDEL INTERNATIONAL LTD.,Chemicals,COROMANDEL
CREDITACCESS GRAMEEN LTD.,Financial Services,CREDITACC
CRISIL LTD.,Services,CRISIL
CROMPTON GREAVES CONSUMER ELECTRICALS LTD.,Consumer Durables,CROMPTON
CUMMINS INDIA LTD.,Capital Goods,CUMMINSIND
CYIENT LTD.,IT,CYIENT
DABUR INDIA LTD.,FMCG,DABUR
DALMIA BHARAT LTD.,Construction Materials,DALBHARAT
DEEPAK NITRITE LTD.,Chemicals,DEEPAKNTR
DELHIVERY LTD.,Services,DELHIVERY
DELTA CORP LTD.,Consumer Services,DELTACORP
DEVYANI INTERNATIONAL LTD.,Consumer Services,DEVYANI
DLF LTD.,Realty,DLF
DIXON TECHNOLOGIES (INDIA) LTD.,Consumer Durables,DIXON
DR. LAL PATHLABS LTD.,Healthcare,LALPATHLAB
DR. REDDY'S LABORATORIES LTD.,Healthcare,DRREDDY
EICHER MOTORS LTD.,Automobile and Auto Components,EICHERMOT
EIH LTD.,Consumer Services,EIHOTEL
EMAMI LTD.,FMCG,EMAMILTD
ENDURANCE TECHNOLOGIES LTD.,Automobile and Auto Components,ENDURANCE
ENGINEERS INDIA LTD.,Construction,ENGINERSIN
ESCORTS KUBOTA LTD.,Automobile and Auto Components,ESCORTS
EXIDE INDUSTRIES LTD.,Automobile and Auto Components,EXIDEIND
FEDERAL BANK LTD.,Financial Services,FEDERALBNK
FIRSTSOURCE SOLUTIONS LTD.,IT,FSL
FORTIS HEALTHCARE LTD.,Healthcare,FORTIS
FSN E-COMMERCE VENTURES LTD.,Consumer Services,NYKAA
GAIL (INDIA) LTD.,Oil Gas & Consumable Fuels,GAIL
GLAND PHARMA LTD.,Healthcare,GLAND
GLENMARK PHARMACEUTICALS LTD.,Healthcare,GLENMARK
GMR AIRPORTS INFRASTRUCTURE LTD.,Services,GMRINFRA
GODREJ CONSUMER PRODUCTS LTD.,FMCG,GODREJCP
GODREJ PROPERTIES LTD.,Realty,GODREJPROP
GRANULES INDIA LTD.,Healthcare,GRANULES
GRASIM INDUSTRIES LTD.,Construction Materials,GRASIM
GUJARAT FLUOROCHEMICALS LTD.,Chemicals,FLUOROCHEM
GUJARAT GAS LTD.,Oil Gas & Consumable Fuels,GUJGASLTD
HAVELLS INDIA LTD.,Consumer Durables,HAVELLS
HCL TECHNOLOGIES LTD.,IT,HCLTECH
HDFC ASSET MANAGEMENT COMPANY LTD.,Financial Services,HDFCAMC
HDFC BANK LTD.,Financial Services,HDFCBANK
HDFC LIFE INSURANCE COMPANY LTD.,Financial Services,HDFCLIFE
HERO MOTOCORP LTD.,Automobile and Auto Components,HEROMOTOCO
HINDALCO INDUSTRIES LTD.,Metals & Mining,HINDALCO
HINDUSTAN AERONAUTICS LTD.,Capital Goods,HAL
HINDUSTAN COPPER LTD.,Metals & Mining,HINDCOPPER
HINDUSTAN PETROLEUM CORPORATION LTD.,Oil Gas & Consumable Fuels,HINDPETRO
HINDUSTAN UNILEVER LTD.,FMCG,HINDUNILVR
HINDUSTAN ZINC LTD.,Metals & Mining,HINDZINC
ICICI BANK LTD.,Financial Services,ICICIBANK
ICICI LOMBARD GENERAL INSURANCE COMPANY LTD.,Financial Services,ICICIGI
ICICI PRUDENTIAL LIFE INSURANCE COMPANY LTD.,Financial Services,ICICIPRULI
IDBI BANK LTD.,Financial Services,IDBI
VODAFONE IDEA LTD.,Telecommunication,IDEA
IDFC FIRST BANK LTD.,Financial Services,IDFCFIRSTB
IDFC LTD.,Financial Services,IDFC
IIFL FINANCE LTD.,Financial Services,IIFL
INDIAMART INTERMESH LTD.,IT,INDIAMART
INDIAN BANK,Financial Services,INDIANB
INDIAN ENERGY EXCHANGE LTD.,Services,IEX
THE INDIAN HOTELS CO. LTD.,Consumer Services,INDHOTEL
INDIAN OVERSEAS BANK,Financial Services,IOB
INDIAN RAILWAY CATERING AND TOURISM CORPORATION LTD.,Consumer Services,IRCTC
INDIAN RAILWAY FINANCE CORPORATION LTD.,Financial Services,IRFC
INTERGLOBE AVIATION LTD.,Services,INDIGO
INDUSIND BANK LTD.,Financial Services,INDUSINDBK
INDUS TOWERS LTD.,Telecommunication,INDUSTOWER
INFOSYS LTD.,IT,INFY
IPCA LABORATORIES LTD.,Healthcare,IPCALAB
IRB INFRASTRUCTURE DEVELOPERS LTD.,Construction,IRB
ITC LTD.,FMCG,ITC
J.K. CEMENT LTD.,Construction Materials,JKCEMENT
JINDAL STAINLESS LTD.,Metals & Mining,JSL
JINDAL STEEL & POWER LTD.,Metals & Mining,JINDALSTEL
JK PAPER LTD.,Forest Materials,JKPAPER
JUBILANT FOODWORKS LTD.,Consumer Services,JUBLFOOD
JUST DIAL LTD.,IT,JUSTDIAL
JYOTHY LABS LTD.,FMCG,JYOTHYLAB
KAJARIA CERAMICS LTD.,Construction Materials,KAJARIACER
KALPATARU PROJECTS INTERNATIONAL LTD.,Power,KPIL
KANSAI NEROLAC PAINTS LTD.,Consumer Durables,KANSAINER
KARUR VYSYA BANK LTD.,Financial Services,KARURVYSYA
KEC INTERNATIONAL LTD.,Capital Goods,KEC
KOTAK MAHINDRA BANK LTD.,Financial Services,KOTAKBANK
KPIT TECHNOLOGIES LTD.,IT,KPITTECH
L&T FINANCE LTD.,Financial Services,L_TFH
L&T TECHNOLOGY SERVICES LTD.,IT,LTTS
LARSEN & TOUBRO LTD.,Construction,LT
LAURUS LABS LTD.,Healthcare,LAURUSLABS
LIC HOUSING FINANCE LTD.,Financial Services,LICHSGFIN
LIFE INSURANCE CORPORATION OF INDIA,Financial Services,LICI
LINDE INDIA LTD.,Chemicals,LINDEINDIA
LUPIN LTD.,Healthcare,LUPIN
MAHINDRA & MAHINDRA LTD.,Automobile and Auto Components,M_M
MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD.,Financial Services,M_MFIN
MANAPPURAM FINANCE LTD.,Financial Services,MANAPPURAM
MANKIND PHARMA LTD.,Healthcare,MANKIND
MARICO LTD.,FMCG,MARICO
MARUTI SUZUKI INDIA LTD.,Automobile and Auto Components,MARUTI
MAX HEALTHCARE INSTITUTE LTD.,Healthcare,MAXHEALTH
MAZAGON DOCK SHIPBUILDERS LTD.,Capital Goods,MAZDOCK
MOTILAL OSWAL FINANCIAL SERVICES LTD.,Financial Services,MOTILALOFS
MRF LTD.,Automobile and Auto Components,MRF
MANGALORE REFINERY & PETROCHEMICALS LTD.,Oil Gas & Consumable Fuels,MRPL
MULTI COMMODITY EXCHANGE OF INDIA LTD.,Services,MCX
MUTHOOT FINANCE LTD.,Financial Services,MUTHOOTFIN
NATIONAL ALUMINIUM CO. LTD.,Metals & Mining,NATIONALUM
NATCO PHARMA LTD.,Healthcare,NATCOPHARM
INFO EDGE (INDIA) LTD.,IT,NAUKRI
NAVIN FLUORINE INTERNATIONAL LTD.,Chemicals,NAVINFLUOR
NBCC (INDIA) LTD.,Construction,NBCC
NESTLE INDIA LTD.,FMCG,NESTLEIND
NIPPON LIFE INDIA ASSET MANAGEMENT LTD.,Financial Services,NAM-INDIA
NLC INDIA LTD.,Power,NLCINDIA
NMDC LTD.,Metals & Mining,NMDC
NTPC LTD.,Power,NTPC
OBEROI REALTY LTD.,Realty,OBEROIRLTY
OIL AND NATURAL GAS CORPORATION LTD.,Oil Gas & Consumable Fuels,ONGC
OIL INDIA LTD.,Oil Gas & Consumable Fuels,OIL
ORACLE FINANCIAL SERVICES SOFTWARE LTD.,IT,OFSS
PAGE INDUSTRIES LTD.,Textiles,PAGEIND
PERSISTENT SYSTEMS LTD.,IT,PERSISTENT
PETRONET LNG LTD.,Oil Gas & Consumable Fuels,PETRONET
PFIZER LTD.,Healthcare,PFIZER
PHOENIX MILLS LTD.,Realty,PHOENIXLTD
PIDILITE INDUSTRIES LTD.,Chemicals,PIDILITIND
PI INDUSTRIES LTD.,Chemicals,PIIND
PIRAMAL ENTERPRISES LTD.,Financial Services,PEL
PUNJAB NATIONAL BANK,Financial Services,PNB
POWER FINANCE CORPORATION LTD.,Financial Services,PFC
POWER GRID CORPORATION OF INDIA LTD.,Power,POWERGRID
PRESTIGE ESTATES PROJECTS LTD.,Realty,PRESTIGE
PVR INOX LTD.,Media Entertainment & Publication,PVRINOX
QUESS CORP LTD.,Services,QUESS
RBL BANK LTD.,Financial Services,RBLBANK
REC LTD.,Financial Services,RECLTD
RELIANCE INDUSTRIES LTD.,Oil Gas & Consumable Fuels,RELIANCE
RITES LTD.,Services,RITES
RAIL VIKAS NIGAM LTD.,Construction,RVNL
STEEL AUTHORITY OF INDIA LTD.,Metals & Mining,SAIL
SHREE CEMENT LTD.,Construction Materials,SHREECEM
SHRIRAM FINANCE LTD.,Financial Services,SHRIRAMFIN
SIEMENS LTD.,Capital Goods,SIEMENS
SONA BLW PRECISION FORGINGS LTD.,Automobile and Auto Components,SONACOMS
STATE BANK OF INDIA,Financial Services,SBIN
STAR HEALTH AND ALLIED INSURANCE COMPANY LTD.,Financial Services,STARHEALTH
SUN PHARMACEUTICAL INDUSTRIES LTD.,Healthcare,SUNPHARMA
SUN TV NETWORK LTD.,Media Entertainment & Publication,SUNTV
SUPREME INDUSTRIES LTD.,Construction Materials,SUPREMEIND
SUZLON ENERGY LTD.,Capital Goods,SUZLON
SYNGENE INTERNATIONAL LTD.,Healthcare,SYNGENE
TATA CHEMICALS LTD.,Chemicals,TATACHEM
TATA COMMUNICATIONS LTD.,Telecommunication,TATACOMM
TATA CONSULTANCY SERVICES LTD.,IT,TCS
TATA CONSUMER PRODUCTS LTD.,FMCG,TATACONSUM
TATA ELXSI LTD.,IT,TATAELXSI
TATA MOTORS LTD.,Automobile and Auto Components,TATAMOTORS
TATA POWER CO. LTD.,Power,TATAPOWER
TATA STEEL LTD.,Metals & Mining,TATASTEEL
TATA TECHNOLOGIES LTD.,IT,TATATECH
TECH MAHINDRA LTD.,IT,TECHM
THE RAMCO CEMENTS LTD.,Construction Materials,RAMCOCEM
THERMAX LTD.,Capital Goods,THERMAX
TITAN COMPANY LTD.,Consumer Durables,TITAN
TORRENT PHARMACEUTICALS LTD.,Healthcare,TORNTPHARM
TORRENT POWER LTD.,Power,TORNTPOWER
TRENT LTD.,Consumer Services,TRENT
TVS MOTOR COMPANY LTD.,Automobile and Auto Components,TVSMOTOR
UNITED BREWERIES LTD.,FMCG,UBL
UCO BANK,Financial Services,UCOBANK
ULTRATECH CEMENT LTD.,Construction Materials,ULTRACEMCO
UNION BANK OF INDIA,Financial Services,UNIONBANK
UNO MINDA LTD.,Automobile and Auto Components,UNOMINDA
UPL LTD.,Chemicals,UPL
VARUN BEVERAGES LTD.,FMCG,VBL
VEDANTA LTD.,Metals & Mining,VEDL
VOLTAS LTD.,Consumer Durables,VOLTAS
WIPRO LTD.,IT,WIPRO
YES BANK LTD.,Financial Services,YESBANK
ZEE ENTERTAINMENT ENTERPRISES LTD.,Media Entertainment & Publication,ZEEL
ZENSAR TECHNOLOGIES LTD.,IT,ZENSARTECH
ZYDUS LIFESCIENCES LTD.,Healthcare,ZYDUSLIFE
'''
        df = pd.read_csv(io.StringIO(nifty_500_csv))
        df.rename(columns={'Symbol': 'Symbol', 'Company Name': 'Security Name'}, inplace=True)
        df['Symbol_NS'] = df['Symbol'] + '.NS'
        df['label'] = df['Security Name'] + ' (' + df['Symbol'] + ')'
        return df[['Symbol_NS', 'Security Name', 'label']].set_index('Symbol_NS')
    except Exception as e:
        st.error(f"Failed to load stock list: {e}")
        return None